# this compose file sets up the services required
# for a full-fledged standalone Karabo installation:
# - a RabbitMQ broker
# - a InfluxDB logging backend - note this is still a 1.7.X version
# - a Grafana frontend for Influx

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: karabo-mq
    environment:
      # if you change these, be sure to adapt the var/environment/KARABO_BROKER definition
      RABBITMQ_DEFAULT_USER: xfel
      RABBITMQ_DEFAULT_PASS: karabo
    ports:
      # if you change these, be sure to adapt the var/environment/KARABO_BROKER definition
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12

    restart: unless-stopped

  influxdb:
    # InfluxDB2 is currently not supported
    image: influxdb:1.7.8
    container_name: karabo-influxdb
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      INFLUXDB_ADMIN_ENABLED: 1
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_HTTP_AUTH_ENABLED: false
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8086'"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb
      - ./influxdb-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

  grafana:
    # works with, and is provisioned with the influx data source
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana_provisioning:/etc/grafana/provisioning/datasources
    restart: unless-stopped

  karabo:
    build: ./karabo
    platform: linux/amd64
    ports:
      - "44444:44444"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    volumes:
      - karabo-installation:/opt/karabo
    security_opt:
      - label=disable
    restart: unless-stopped

volumes:
  influxdb-data:
  rabbitmq-data:
  rabbitmq-logs:
  grafana-storage:
  karabo-installation:
